name = "CC Challenge"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c7cf7da555afad6efe7bc59cca320130f28b6e5110d5ceb13990a2dfa3334a0"

[versions]
forge = "47.0.34"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
