name = "CC Challenge"
author = "SirEdvin"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "582b39b41cae728afd86a6999a94d9e5d6048067d218013d4037ced6f725e372"

[versions]
forge = "47.0.34"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
