name = "CC Challenge"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ac3b639faff6db413d77ae06eede71e7534d0af4eb9e04b7a7bf13c47ab0965"

[versions]
forge = "47.0.34"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
