name = "CC Challenge"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c37cf70e2ba79475bf17e2249868979e0cddf98b4212526057dc61bedb2478a"

[versions]
forge = "47.0.34"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
